#Rename the file to be docker-compose
#docker-compose scale up file
#To execute this docker-compose yml file use docker-compose up -d

#selenium-hub: equivalent to manually running the command docker run -d -p 4444:4444 --name selenium-hub  -P selenium/hub
version: "3"
services:
    selenium-hub:
      restart: always
      image: selenium/hub:3.11.0-californium
      ports:
        - 4444:4444
    #selenium-chrome equivalent to manually running the command docker run -d --link selenium-hub:hub -P --name chrome selenium/node-chrome-debug
    chromenode:
      restart: always
      image: selenium/node-chrome-debug:3.11.0-californium
      environment:
        - HUB_HOST=selenium-hub
        - HUB_PORT=4444
        - NODE_MAX_INSTANCE=5
        - NODE_MAX_SESSION=5
      ports:
        - 5900
      #stdin_open: true
      depends_on:
        - selenium-hub
        
    #selenium-firefox equivalent to manually running the command docker run -d --link selenium-hub:hub -P --name firefox selenium/node-firefox-debug
    firefoxnode:
      restart: always
      image: selenium/node-firefox-debug:3.11.0-californium
      environment:
        - HUB_HOST=selenium-hub
        - HUB_PORT=4444
        - NODE_MAX_INSTANCE=5
        - NODE_MAX_SESSION=5
      ports:
        - 5900
      depends_on:
        - selenium-hub
        
    saurabh-module:
      image: skdocker/selenium-docker
      depends_on:
        - chromenode
        - firefoxnode
      environment:
        - HUB_HOST=selenium-hub
        - TESTNG_FILE=testng_surefire_8.xml
        - BROWSER=CHROME 
      ports:
        - 5900
      volumes:
        - /c/Users/kakka/output:/usr/share/udemy/RESULT_LOG
        